# Continouos Integration action.
# ~~~~
name: "CI"
on:
  release:
    types: [ created ]
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, '**' ]
  schedule:
    - cron: '45 3 * * 1'

jobs:
  validate:
    name: Validate Code (Play ${{ matrix.play }})
    if: "(github.event.release || github.event.release.prerelease) == false"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        play: [ '2.9', '3.0' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: '17'

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Check Project Code
        run: sbt -Dplay.version=${{ matrix.play }} validateCode

      - name: Upload ScalaStyle Report (XML)
        if: matrix.play == '2.9'
        uses: actions/upload-artifact@v4
        with:
          name: scalastyle-reports
          path: ${{github.workspace}}/target/scalastyle-report/

  build:
    name: Build (Play ${{ matrix.play }} / Scala ${{ matrix.scala }})
    if: "(github.event.release || github.event.release.prerelease) == false"
    needs: [ validate ]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { play: '2.9', scala: '2.13.18', jdk: '17' }
          - { play: '3.0', scala: '2.13.18', jdk: '17' }
          - { play: '3.0', scala: '3.3.6',   jdk: '17' }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: ${{ matrix.jdk }}

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Perform Build / Test
        run: sbt -Dplay.version=${{ matrix.play }} ++${{ matrix.scala }} compile test

  optional-build:
    name: Build / Optional (Play ${{ matrix.play }} / Scala ${{ matrix.scala }} / JDK ${{ matrix.jdk }})
    if: "(github.event.release || github.event.release.prerelease) == false"
    continue-on-error: ${{ matrix.experimental }}
    needs: [ validate ]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { play: '2.9', scala: '2.13.18', jdk: '21', experimental: true }
          - { play: '3.0', scala: '2.13.18', jdk: '21', experimental: true }
          - { play: '3.0', scala: '3.3.6',   jdk: '21', experimental: true }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: ${{ matrix.jdk }}

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Perform Build / Test
        run: sbt -Dplay.version=${{ matrix.play }} ++${{ matrix.scala }} compile test

  ready:
    name: Ready to Merge
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ready to merge!"

  publish:
    name: Publish to Sonatype (Play ${{ matrix.play }})
    if: "github.event.release || github.event.release.prerelease"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        play: [ '2.9', '3.0' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Publish package
        run: sbt -Dplay.version=${{ matrix.play }} ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
